# Interest categories for garden-entry details.
# Keys are category names; values are ordered lists of suggested detail labels.

INTEREST_CATEGORIES: dict[str, list[str]] = {
    "Music": [
        "Favourite artists",
        "Favourite songs",
        "Favourite genres",
        "Favourite albums",
        "Concerts attended",
        "Dream concerts",
        "Instruments they play",
        "Music they make",
    ],
    "Movies": [
        "Favourite films",
        "Favourite directors",
        "Favourite genres",
        "Favourite actors",
        "Themes they love",
        "All-time favourite film",
        "Films they quote",
    ],
    "TV & Streaming": [
        "Favourite shows",
        "Currently watching",
        "Favourite genres",
        "Content creators they follow",
        "Podcasts they love",
        "Guilty pleasures",
        "Rewatched shows",
    ],
    "Books": [
        "Favourite authors",
        "Favourite genres",
        "Currently reading",
        "Favourite titles",
        "Favourite series",
        "Book clubs",
        "Books that changed them",
    ],
    "Food & Drink": [
        "Favourite cuisines",
        "Favourite restaurants",
        "Coffee order",
        "Drink of choice",
        "Comfort food",
        "Dietary preferences",
        "Allergies or restrictions",
        "They love to cook",
    ],
    "Travel": [
        "Places visited",
        "Dream destinations",
        "Favourite city",
        "Travel style",
        "Languages spoken",
        "Places they lived",
        "Next trip planned",
    ],
    "Sports & Fitness": [
        "Favourite sports",
        "Favourite teams",
        "Activities they enjoy",
        "Fitness goals",
        "Outdoor pursuits",
        "Sports they played growing up",
    ],
    "Work & Career": [
        "Industry",
        "Current role",
        "Career goals",
        "Dream job",
        "Side projects",
        "Skills they are proud of",
        "Work style",
        "How they found their path",
    ],
    "Hobbies": [
        "Creative pursuits",
        "Collections",
        "Video games they play",
        "Board games they love",
        "Crafts",
        "DIY projects",
        "Other hobbies",
    ],
    "Personal": [
        "Values",
        "Life goals",
        "Love languages",
        "What energises them",
        "What drains them",
        "Myers-Briggs or personality type",
        "Quirks",
        "Pet peeves",
        "How they recharge",
    ],
    "General": [
        "Birthday",
        "Hometown",
        "Current city",
        "Pets",
        "Fun fact",
        "How we met",
        "Custom",
    ],
}

# Display order for category sections
CATEGORY_ORDER: list[str] = list(INTEREST_CATEGORIES.keys())

# Single-char icons per category (text-safe, no emoji dependency)
CATEGORY_ICONS: dict[str, str] = {
    "Music": "♪",
    "Movies": "◈",
    "TV & Streaming": "▷",
    "Books": "☷",
    "Food & Drink": "◉",
    "Travel": "◎",
    "Sports & Fitness": "▣",
    "Work & Career": "▤",
    "Hobbies": "✦",
    "Personal": "♡",
    "General": "·",
}
